services:
  - type: web
    name: pharmia-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildFilter:
      paths:
        - "backend/**"
    build: npm install
    start: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
  - type: static
    name: pharmia-frontend-new
    buildCommand: npm install && npm run build
    publishDir: dist
    buildFilter:
      ignoredPaths:
        - "backend/**"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
